# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160609_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_profile_picture',
            field=models.ImageField(default='default/profile.png', upload_to=''),
        ),
    ]
