# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_default_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_profile_picture',
            field=models.ImageField(default='D:\\GitHub Open Source\\blog 1\\media_cdndefault/profile.png', upload_to=''),
        ),
    ]
